name: jodikafit
favicon: null
layout_spectrum: 0.006825913209468126
typography_spectrum: 0.10828104219399393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2247894445899874
  lightness: 0.7631049284245819
  saturation: 0.6113292118534446
  rhythmicContrast: 0.45603493321686983
purpose: []
